CREATE TABLE alumni (
    alumniID        INT         NOT NULL,
    fName           VARCHAR(20) NOT NULL,
    lName           VARCHAR(20) NOT NULL,
    email           VARCHAR(50),
    phone           VARCHAR(10),
    DOB             DATE,
    gender          VARCHAR(1),
    ethnicity       VARCHAR(1),
    website         VARCHAR(100),
    linkedIn_link   VARCHAR(100),
    twitter_link    VARCHAR(100),
    facebook_link   VARCHAR(100),
    instagram_link  VARCHAR(100),
    guestSpeakerYN  VARCHAR(1),
    newsLetterYN    VARCHAR(1),
    imageThumb      VARCHAR(200),
    imageNormal     VARCHAR(200),
    description     VARCHAR(500),
    deceasedYN      VARCHAR(1),
    deceasedDT      DATE,
    deceasedNotes   VARCHAR(500),
    CONSTRAINT PK_alumniID PRIMARY KEY CLUSTERED (alumniID)
);
